version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - ArthurAssuncao
  ignore:
  - dependency-name: stylelint
    versions:
    - 13.8.0
    - 13.9.0
  - dependency-name: netlify-cli
    versions:
    - 2.69.11
    - 3.4.6
  - dependency-name: netlify
    versions:
    - 6.0.7
    - 6.1.6
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: stylis
    versions:
    - 4.0.6
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: markdownlint
    versions:
    - 0.22.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
