version: "2.2.1"
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "build/"
  - ".[!.]*"
  - ".png"
  - ".pdf"
  - ".gif"
  - ".jpeg"
  - ".jpg"
  - ".svg"
plugins:
  editorconfig:
    enabled: false
    channel: beta
    config:
      editorconfig: .editorconfig
  git-legal:
    enabled: false
    config:
      allow_affero_copyleft: false
      allow_strong_copyleft: false
      allow_unknown_libraries: true
  haml-lint:
    enabled: true
  markdownlint:
    enabled: true
  stylelint:
    enabled: false
  eslint:
    enabled: true
  tslint:
    enabled: false
    config: tslint.json
