version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:8.10.0
commands:
  react-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: React Build
          command: yarn build
  install-netlify:
    steps:
      - run:
          name: Install Netlify cli
          command: sudo npm install netlify-cli -g
jobs:
  build:
    executor: node-executor
    steps:
      - react-build
      - persist_to_workspace:
          root: ./
          paths:
            - public
  # deploy-stage:
  #   executor: node-executor
  #   working_directory: ~/ArthurAssuncao.com
  #   steps:
  #     - react-build
  #     - run:
  #         name: Netlify Deploy
  #         command: ./node_modules/.bin/netlify deploy --dir=public
  # test:
  #   executor: node-executor
  #   working_directory: ~/ArthurAssuncao.com
  #   steps:
  #     - react-build
  #     - run:
  #         name: Test
  #         command: yarn test
  deploy-prod:
    executor: node-executor
    working_directory: ~/tmp/ArthurAssuncao.com
    steps:
      - install-netlify
      - run:
          name: Netlify Deploy
          command: netlify deploy --prod --dir=public
workflows:
  version: 2
  build-deploy:
    jobs:
      # - install-netlify:
      #     filters:
      #       branches:
      #         ignore:
      #           - develop
      #           - /feature-.*/
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      # - test:
      #     requires:
      #       - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
