version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:8.10.0
commands:
  react-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: React Build
          command: yarn build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - staging
      - test:
          requires:
            - build
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  build:
    executor: node-executor
    working_directory: ~/ArthurAssuncao.com
    steps:
      - react-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --dir=public
  test:
    executor: node-executor
    working_directory: ~/ArthurAssuncao.com
    steps:
      - react-build
      - run:
          name: Test
          command: yarn test
  release:
    executor: node-executor
    working_directory: ~/ArthurAssuncao.com
    steps:
      - react-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --prod --dir=public
